#! /bin/bash -e
SG_HOST=sg-eth
./gen-package.sh
PKG=$(ls -r packages | head -1)
scp packages/$PKG pi@$SG_HOST:
ssh pi@$SG_HOST sudo apt install --reinstall ./$PKG
#ssh pi@$SG_HOST sudo systemctl restart sg-control
